-- Sumi ink — neutral gray borders, kept deliberately colorless.
-- NOT generated by matugen: appearance.wallpaperTheming.enableAppsAndShell is
-- set to false precisely so this file survives wallpaper changes untouched.
-- (matugen would target this exact path; see ~/.config/matugen/config.toml.)
--
-- Loaded after hyprland/general.lua, so these values win over the defaults there.
-- Note: hl.config only accepts a SINGLE color here — a multi-stop gradient string
-- is rejected silently and general.lua's value survives instead.

hl.config({
    general = {
        col = {
            -- neutral gray, the original pre-theming value
            active_border   = "rgba(47474777)",
            -- barely there
            inactive_border = "rgba(1b1b1b33)",
        },
    },
    misc = {
        -- neutral near-black, same base as the shell surfaces
        background_color = "rgba(0E0E0EFF)",
    },
})

hl.window_rule({
    match        = { pin = 1 },
    -- white marks pinned windows
    border_color = "rgba(ffffffAA) rgba(ffffff77)",
})
